### ISSUE TITLE
How to use ndk to build mesa

### ISSUE THREAD

**Issue by zhipenggong** [Vera-Firefly/android-mesa-build#1]
I met the dependency error when building mesa with the cross file
    dep_android = [
      dependency('cutils'),
      dependency('hardware'),
      dependency('sync'),
      dependency('backtrace')
    ]
Could you please tell me how to resolve these dependency?
Thank you very much

**Comment by Vera-Firefly** [comment]
Remove dependent 'cutils', which is not required by Pojav
